-- Refresh TaxonomyRule version v2.1 with a broader bilingual rule set.
-- Execute against the mem9 database, for example:
--   mysql -D mem9 < prisma/taxonomy-v2.1.sql
-- Note: this file now writes version = v2.1 for production compatibility.

SET NAMES utf8mb4;

START TRANSACTION;

DELETE FROM `TaxonomyRule`
WHERE `version` = 'v2.1';

INSERT INTO `TaxonomyRule` (
  `id`,
  `version`,
  `category`,
  `label`,
  `lang`,
  `matchType`,
  `pattern`,
  `weight`,
  `enabled`
) VALUES
  -- Identity rules
  ('v2.1-zh-CN-identity-工程师', 'v2.1', 'identity', '职业身份', 'zh-CN', 'keyword', '工程师', 5, true),
  ('v2.1-zh-CN-identity-程序员', 'v2.1', 'identity', '职业身份', 'zh-CN', 'keyword', '程序员', 5, true),
  ('v2.1-zh-CN-identity-开发者', 'v2.1', 'identity', '职业身份', 'zh-CN', 'keyword', '开发者', 5, true),
  ('v2.1-zh-CN-identity-后端', 'v2.1', 'identity', '职业身份', 'zh-CN', 'keyword', '后端', 5, true),
  ('v2.1-zh-CN-identity-前端', 'v2.1', 'identity', '职业身份', 'zh-CN', 'keyword', '前端', 5, true),
  ('v2.1-zh-CN-identity-全栈', 'v2.1', 'identity', '职业身份', 'zh-CN', 'keyword', '全栈', 5, true),
  ('v2.1-zh-CN-identity-产品经理', 'v2.1', 'identity', '职业身份', 'zh-CN', 'keyword', '产品经理', 5, true),
  ('v2.1-zh-CN-identity-设计师', 'v2.1', 'identity', '职业身份', 'zh-CN', 'keyword', '设计师', 5, true),
  ('v2.1-zh-CN-identity-创业者', 'v2.1', 'identity', '职业身份', 'zh-CN', 'keyword', '创业者', 5, true),
  ('v2.1-zh-CN-identity-研究员', 'v2.1', 'identity', '职业身份', 'zh-CN', 'keyword', '研究员', 5, true),
  ('v2.1-zh-CN-identity-学生', 'v2.1', 'identity', '职业身份', 'zh-CN', 'keyword', '学生', 5, true),
  ('v2.1-zh-CN-identity-老师', 'v2.1', 'identity', '职业身份', 'zh-CN', 'keyword', '老师', 5, true),
  ('v2.1-zh-CN-identity-运维', 'v2.1', 'identity', '职业身份', 'zh-CN', 'keyword', '运维', 5, true),
  ('v2.1-zh-CN-identity-运营', 'v2.1', 'identity', '职业身份', 'zh-CN', 'keyword', '运营', 5, true),
  ('v2.1-zh-CN-identity-架构师', 'v2.1', 'identity', '职业身份', 'zh-CN', 'keyword', '架构师', 5, true),
  ('v2.1-zh-CN-identity-技术负责人', 'v2.1', 'identity', '职业身份', 'zh-CN', 'phrase', '技术负责人', 5, true),
  ('v2.1-zh-CN-identity-维护者', 'v2.1', 'identity', '职业身份', 'zh-CN', 'keyword', '维护者', 5, true),
  ('v2.1-zh-CN-identity-工作机器人', 'v2.1', 'identity', '职业身份', 'zh-CN', 'phrase', '工作机器人', 5, true),
  ('v2.1-zh-CN-identity-主人', 'v2.1', 'identity', '职业身份', 'zh-CN', 'keyword', '主人', 5, true),
  ('v2.1-en-US-identity-engineer', 'v2.1', 'identity', 'Role', 'en-US', 'keyword', 'engineer', 5, true),
  ('v2.1-en-US-identity-developer', 'v2.1', 'identity', 'Role', 'en-US', 'keyword', 'developer', 5, true),
  ('v2.1-en-US-identity-programmer', 'v2.1', 'identity', 'Role', 'en-US', 'keyword', 'programmer', 5, true),
  ('v2.1-en-US-identity-backend-engineer', 'v2.1', 'identity', 'Role', 'en-US', 'phrase', 'backend engineer', 5, true),
  ('v2.1-en-US-identity-frontend-engineer', 'v2.1', 'identity', 'Role', 'en-US', 'phrase', 'frontend engineer', 5, true),
  ('v2.1-en-US-identity-full-stack', 'v2.1', 'identity', 'Role', 'en-US', 'phrase', 'full stack', 5, true),
  ('v2.1-en-US-identity-full-stack-2', 'v2.1', 'identity', 'Role', 'en-US', 'phrase', 'full-stack', 5, true),
  ('v2.1-en-US-identity-product-manager', 'v2.1', 'identity', 'Role', 'en-US', 'phrase', 'product manager', 5, true),
  ('v2.1-en-US-identity-designer', 'v2.1', 'identity', 'Role', 'en-US', 'keyword', 'designer', 5, true),
  ('v2.1-en-US-identity-founder', 'v2.1', 'identity', 'Role', 'en-US', 'keyword', 'founder', 5, true),
  ('v2.1-en-US-identity-researcher', 'v2.1', 'identity', 'Role', 'en-US', 'keyword', 'researcher', 5, true),
  ('v2.1-en-US-identity-student', 'v2.1', 'identity', 'Role', 'en-US', 'keyword', 'student', 5, true),
  ('v2.1-en-US-identity-teacher', 'v2.1', 'identity', 'Role', 'en-US', 'keyword', 'teacher', 5, true),
  ('v2.1-en-US-identity-tech-lead', 'v2.1', 'identity', 'Role', 'en-US', 'phrase', 'tech lead', 5, true),
  ('v2.1-en-US-identity-maintainer', 'v2.1', 'identity', 'Role', 'en-US', 'keyword', 'maintainer', 5, true),
  ('v2.1-en-US-identity-operator', 'v2.1', 'identity', 'Role', 'en-US', 'keyword', 'operator', 5, true),
  ('v2.1-en-US-identity-architect', 'v2.1', 'identity', 'Role', 'en-US', 'keyword', 'architect', 5, true),
  ('v2.1-en-US-identity-work-robot', 'v2.1', 'identity', 'Role', 'en-US', 'phrase', 'work robot', 5, true),
  ('v2.1-en-US-identity-owner', 'v2.1', 'identity', 'Role', 'en-US', 'keyword', 'owner', 5, true),
  ('v2.1-en-US-identity-works-at-pingcap', 'v2.1', 'identity', 'Role', 'en-US', 'phrase', 'works at pingcap', 5, true),
  ('v2.1-en-US-identity-pingcap-employee', 'v2.1', 'identity', 'Role', 'en-US', 'phrase', 'pingcap employee', 5, true),
  ('v2.1-en-US-identity-platform-operation-and-maintenance', 'v2.1', 'identity', 'Role', 'en-US', 'phrase', 'platform operation and maintenance', 5, true),
  ('v2.1-zh-CN-identity-北京时间', 'v2.1', 'identity', 'Profile', 'zh-CN', 'keyword', '北京时间', 5, true),
  ('v2.1-en-US-identity-utcplus8', 'v2.1', 'identity', 'Profile', 'en-US', 'phrase', 'utc+8', 5, true),
  ('v2.1-en-US-identity-beijing-time', 'v2.1', 'identity', 'Profile', 'en-US', 'phrase', 'beijing time', 5, true),
  ('v2.1-en-US-identity-timezone', 'v2.1', 'identity', 'Profile', 'en-US', 'keyword', 'timezone', 5, true),
  ('v2.1-en-US-identity-working-hours', 'v2.1', 'identity', 'Profile', 'en-US', 'phrase', 'working hours', 5, true),
  ('v2.1-en-US-identity-work-hours', 'v2.1', 'identity', 'Profile', 'en-US', 'phrase', 'work hours', 5, true),
  -- Emotion rules
  ('v2.1-zh-CN-emotion-开心', 'v2.1', 'emotion', '情绪', 'zh-CN', 'keyword', '开心', 4, true),
  ('v2.1-zh-CN-emotion-高兴', 'v2.1', 'emotion', '情绪', 'zh-CN', 'keyword', '高兴', 4, true),
  ('v2.1-zh-CN-emotion-快乐', 'v2.1', 'emotion', '情绪', 'zh-CN', 'keyword', '快乐', 4, true),
  ('v2.1-zh-CN-emotion-兴奋', 'v2.1', 'emotion', '情绪', 'zh-CN', 'keyword', '兴奋', 4, true),
  ('v2.1-zh-CN-emotion-激动', 'v2.1', 'emotion', '情绪', 'zh-CN', 'keyword', '激动', 4, true),
  ('v2.1-zh-CN-emotion-满足', 'v2.1', 'emotion', '情绪', 'zh-CN', 'keyword', '满足', 4, true),
  ('v2.1-zh-CN-emotion-放松', 'v2.1', 'emotion', '情绪', 'zh-CN', 'keyword', '放松', 4, true),
  ('v2.1-zh-CN-emotion-哈哈哈', 'v2.1', 'emotion', '情绪', 'zh-CN', 'keyword', '哈哈哈', 4, true),
  ('v2.1-zh-CN-emotion-焦虑', 'v2.1', 'emotion', '情绪', 'zh-CN', 'keyword', '焦虑', 4, true),
  ('v2.1-zh-CN-emotion-难过', 'v2.1', 'emotion', '情绪', 'zh-CN', 'keyword', '难过', 4, true),
  ('v2.1-zh-CN-emotion-伤心', 'v2.1', 'emotion', '情绪', 'zh-CN', 'keyword', '伤心', 4, true),
  ('v2.1-zh-CN-emotion-生气', 'v2.1', 'emotion', '情绪', 'zh-CN', 'keyword', '生气', 4, true),
  ('v2.1-zh-CN-emotion-郁闷', 'v2.1', 'emotion', '情绪', 'zh-CN', 'keyword', '郁闷', 4, true),
  ('v2.1-zh-CN-emotion-烦躁', 'v2.1', 'emotion', '情绪', 'zh-CN', 'keyword', '烦躁', 4, true),
  ('v2.1-zh-CN-emotion-失望', 'v2.1', 'emotion', '情绪', 'zh-CN', 'keyword', '失望', 4, true),
  ('v2.1-zh-CN-emotion-崩溃', 'v2.1', 'emotion', '情绪', 'zh-CN', 'keyword', '崩溃', 4, true),
  ('v2.1-zh-CN-emotion-轻松', 'v2.1', 'emotion', '情绪', 'zh-CN', 'keyword', '轻松', 4, true),
  ('v2.1-zh-CN-emotion-紧张', 'v2.1', 'emotion', '情绪', 'zh-CN', 'keyword', '紧张', 4, true),
  ('v2.1-zh-CN-emotion-有压力', 'v2.1', 'emotion', '情绪', 'zh-CN', 'keyword', '有压力', 4, true),
  ('v2.1-zh-CN-emotion-压力很大', 'v2.1', 'emotion', '情绪', 'zh-CN', 'keyword', '压力很大', 4, true),
  ('v2.1-en-US-emotion-happy', 'v2.1', 'emotion', 'Emotion', 'en-US', 'keyword', 'happy', 4, true),
  ('v2.1-en-US-emotion-excited', 'v2.1', 'emotion', 'Emotion', 'en-US', 'keyword', 'excited', 4, true),
  ('v2.1-en-US-emotion-thrilled', 'v2.1', 'emotion', 'Emotion', 'en-US', 'keyword', 'thrilled', 4, true),
  ('v2.1-en-US-emotion-relieved', 'v2.1', 'emotion', 'Emotion', 'en-US', 'keyword', 'relieved', 4, true),
  ('v2.1-en-US-emotion-relaxed', 'v2.1', 'emotion', 'Emotion', 'en-US', 'keyword', 'relaxed', 4, true),
  ('v2.1-en-US-emotion-grateful', 'v2.1', 'emotion', 'Emotion', 'en-US', 'keyword', 'grateful', 4, true),
  ('v2.1-en-US-emotion-hahaha', 'v2.1', 'emotion', 'Emotion', 'en-US', 'keyword', 'hahaha', 4, true),
  ('v2.1-en-US-emotion-lol', 'v2.1', 'emotion', 'Emotion', 'en-US', 'keyword', 'lol', 4, true),
  ('v2.1-en-US-emotion-anxious', 'v2.1', 'emotion', 'Emotion', 'en-US', 'keyword', 'anxious', 4, true),
  ('v2.1-en-US-emotion-stressed', 'v2.1', 'emotion', 'Emotion', 'en-US', 'keyword', 'stressed', 4, true),
  ('v2.1-en-US-emotion-sad', 'v2.1', 'emotion', 'Emotion', 'en-US', 'keyword', 'sad', 4, true),
  ('v2.1-en-US-emotion-upset', 'v2.1', 'emotion', 'Emotion', 'en-US', 'keyword', 'upset', 4, true),
  ('v2.1-en-US-emotion-angry', 'v2.1', 'emotion', 'Emotion', 'en-US', 'keyword', 'angry', 4, true),
  ('v2.1-en-US-emotion-frustrated', 'v2.1', 'emotion', 'Emotion', 'en-US', 'keyword', 'frustrated', 4, true),
  ('v2.1-en-US-emotion-worried', 'v2.1', 'emotion', 'Emotion', 'en-US', 'keyword', 'worried', 4, true),
  ('v2.1-en-US-emotion-overwhelmed', 'v2.1', 'emotion', 'Emotion', 'en-US', 'keyword', 'overwhelmed', 4, true),
  ('v2.1-en-US-emotion-burned-out', 'v2.1', 'emotion', 'Emotion', 'en-US', 'phrase', 'burned out', 4, true),
  ('v2.1-en-US-emotion-burnout', 'v2.1', 'emotion', 'Emotion', 'en-US', 'keyword', 'burnout', 4, true),
  -- Preference and policy rules
  ('v2.1-zh-CN-preference-喜欢', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'keyword', '喜欢', 4, true),
  ('v2.1-zh-CN-preference-偏爱', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'keyword', '偏爱', 4, true),
  ('v2.1-zh-CN-preference-热爱', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'keyword', '热爱', 4, true),
  ('v2.1-zh-CN-preference-想要', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'keyword', '想要', 4, true),
  ('v2.1-zh-CN-preference-希望', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'keyword', '希望', 4, true),
  ('v2.1-zh-CN-preference-不喜欢', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'keyword', '不喜欢', 4, true),
  ('v2.1-zh-CN-preference-讨厌', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'keyword', '讨厌', 4, true),
  ('v2.1-zh-CN-preference-不想', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'keyword', '不想', 4, true),
  ('v2.1-zh-CN-preference-偏好', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'keyword', '偏好', 4, true),
  ('v2.1-zh-CN-preference-默认跟随语言回复', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'phrase', '默认跟随语言回复', 4, true),
  ('v2.1-zh-CN-preference-用中文回复', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'phrase', '用中文回复', 4, true),
  ('v2.1-zh-CN-preference-用英文回复', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'phrase', '用英文回复', 4, true),
  ('v2.1-zh-CN-preference-简洁但不丢信息', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'phrase', '简洁但不丢信息', 4, true),
  ('v2.1-zh-CN-preference-简洁但不要丢信息', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'phrase', '简洁但不要丢信息', 4, true),
  ('v2.1-zh-CN-preference-节省-token', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'phrase', '节省 token', 4, true),
  ('v2.1-zh-CN-preference-省-token', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'phrase', '省 token', 4, true),
  ('v2.1-zh-CN-preference-保存-token', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'phrase', '保存 token', 4, true),
  ('v2.1-zh-CN-preference-不保存任何人的隐私数据', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'phrase', '不保存任何人的隐私数据', 4, true),
  ('v2.1-zh-CN-preference-团队可见', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'keyword', '团队可见', 4, true),
  ('v2.1-zh-CN-preference-默认按团队可见标准处理', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'phrase', '默认按团队可见标准处理', 4, true),
  ('v2.1-zh-CN-preference-不要-force-push', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'phrase', '不要 force push', 4, true),
  ('v2.1-zh-CN-preference-不要-rewrite-history', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'phrase', '不要 rewrite history', 4, true),
  ('v2.1-zh-CN-preference-不要改无关配置', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'phrase', '不要改无关配置', 4, true),
  ('v2.1-zh-CN-preference-只在被直接提及时处理', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'phrase', '只在被直接提及时处理', 4, true),
  ('v2.1-zh-CN-preference-需要直接提及', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'phrase', '需要直接提及', 4, true),
  ('v2.1-zh-CN-preference-必须', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'keyword', '必须', 4, true),
  ('v2.1-zh-CN-preference-不要发送-reminder', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'phrase', '不要发送 reminder', 4, true),
  ('v2.1-zh-CN-preference-不要发-reminder', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'phrase', '不要发 reminder', 4, true),
  ('v2.1-zh-CN-preference-内部使用', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'keyword', '内部使用', 4, true),
  ('v2.1-zh-CN-preference-仅内部使用', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'phrase', '仅内部使用', 4, true),
  ('v2.1-zh-CN-preference-高优先级规则', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'phrase', '高优先级规则', 4, true),
  ('v2.1-zh-CN-preference-规则', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'keyword', '规则', 4, true),
  ('v2.1-zh-CN-preference-策略', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'keyword', '策略', 4, true),
  ('v2.1-zh-CN-preference-如果没有变化', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'phrase', '如果没有变化', 4, true),
  ('v2.1-zh-CN-preference-无变化就退出', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'phrase', '无变化就退出', 4, true),
  ('v2.1-zh-CN-preference-没有变化就退出', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'phrase', '没有变化就退出', 4, true),
  ('v2.1-zh-CN-preference-报告-changed-no-changes', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'phrase', '报告 changed/no changes', 4, true),
  ('v2.1-zh-CN-preference-保持输出简洁', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'phrase', '保持输出简洁', 4, true),
  ('v2.1-zh-CN-preference-不要修改无关配置', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'phrase', '不要修改无关配置', 4, true),
  ('v2.1-zh-CN-preference-不要强推', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'keyword', '不要强推', 4, true),
  ('v2.1-zh-CN-preference-不要改写历史', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'phrase', '不要改写历史', 4, true),
  ('v2.1-zh-CN-preference-需要发送当前报告总结', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'phrase', '需要发送当前报告总结', 4, true),
  ('v2.1-zh-CN-preference-重大变更前先给计划', 'v2.1', 'preference', '偏好与规则', 'zh-CN', 'phrase', '重大变更前先给计划', 4, true),
  ('v2.1-en-US-preference-prefer', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'keyword', 'prefer', 4, true),
  ('v2.1-en-US-preference-favorite', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'keyword', 'favorite', 4, true),
  ('v2.1-en-US-preference-love', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'keyword', 'love', 4, true),
  ('v2.1-en-US-preference-want-to', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'want to', 4, true),
  ('v2.1-en-US-preference-would-like', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'would like', 4, true),
  ('v2.1-en-US-preference-dislike', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'keyword', 'dislike', 4, true),
  ('v2.1-en-US-preference-hate', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'keyword', 'hate', 4, true),
  ('v2.1-en-US-preference-do-not-want', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'do not want', 4, true),
  ('v2.1-en-US-preference-concise', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'keyword', 'concise', 4, true),
  ('v2.1-en-US-preference-save-tokens', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'save tokens', 4, true),
  ('v2.1-en-US-preference-should-not', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'should not', 4, true),
  ('v2.1-en-US-preference-do-not', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'do not', 4, true),
  ('v2.1-en-US-preference-must', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'keyword', 'must', 4, true),
  ('v2.1-en-US-preference-only-process', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'only process', 4, true),
  ('v2.1-en-US-preference-require', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'keyword', 'require', 4, true),
  ('v2.1-en-US-preference-internal-only', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'keyword', 'internal-only', 4, true),
  ('v2.1-en-US-preference-team-visibility', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'team visibility', 4, true),
  ('v2.1-en-US-preference-do-not-force-push', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'do not force push', 4, true),
  ('v2.1-en-US-preference-do-not-rewrite-history', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'do not rewrite history', 4, true),
  ('v2.1-en-US-preference-do-not-modify-unrelated-config', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'do not modify unrelated config', 4, true),
  ('v2.1-en-US-preference-modify-unrelated-config', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'modify unrelated config', 4, true),
  ('v2.1-en-US-preference-unrelated-config', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'unrelated config', 4, true),
  ('v2.1-en-US-preference-match-the-user-language', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'match the user language', 4, true),
  ('v2.1-en-US-preference-match-user-language-by-default', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'match user language by default', 4, true),
  ('v2.1-en-US-preference-match-the-user-s-language-by-default', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'match the user''s language by default', 4, true),
  ('v2.1-en-US-preference-assistant-should-match-the-user-s-language-by-default', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'assistant should match the user''s language by default', 4, true),
  ('v2.1-en-US-preference-assistant-should-match-user-s-language-by-default', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'assistant should match user''s language by default', 4, true),
  ('v2.1-en-US-preference-reply-in-english', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'reply in english', 4, true),
  ('v2.1-en-US-preference-reply-in-chinese', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'reply in chinese', 4, true),
  ('v2.1-en-US-preference-do-not-save-private-data', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'do not save private data', 4, true),
  ('v2.1-en-US-preference-ignore-broad-mentions', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'ignore broad mentions', 4, true),
  ('v2.1-en-US-preference-directly-mentioned', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'directly mentioned', 4, true),
  ('v2.1-en-US-preference-individually-mentioned', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'individually mentioned', 4, true),
  ('v2.1-en-US-preference-group-chat-handling-rule', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'group chat handling rule', 4, true),
  ('v2.1-en-US-preference-high-priority-cross-session-rule', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'high-priority cross-session rule', 4, true),
  ('v2.1-en-US-preference-no-follow-up-reminder', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'no follow-up reminder', 4, true),
  ('v2.1-en-US-preference-if-no-changes', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'if no changes', 4, true),
  ('v2.1-en-US-preference-no-changes-and-exit', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'no changes and exit', 4, true),
  ('v2.1-en-US-preference-push-result', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'push result', 4, true),
  ('v2.1-en-US-preference-changed-no-changes', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'changed/no changes', 4, true),
  ('v2.1-en-US-preference-should-be-concise', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'should be concise', 4, true),
  ('v2.1-en-US-preference-work-in', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'work in', 4, true),
  ('v2.1-en-US-preference-should-push-to-origin', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'should push to origin', 4, true),
  ('v2.1-en-US-preference-current-branch', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'current branch', 4, true),
  ('v2.1-en-US-preference-preserve-ssh-host-alias', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'preserve ssh host alias', 4, true),
  ('v2.1-en-US-preference-requires-the-current-report-summary', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'requires the current report summary', 4, true),
  ('v2.1-en-US-preference-default-to-beijing-time', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'default to beijing time', 4, true),
  ('v2.1-en-US-preference-should-default-to-beijing-time', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'should default to beijing time', 4, true),
  ('v2.1-en-US-preference-should-be-called-bosn', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'should be called bosn', 4, true),
  ('v2.1-en-US-preference-called-bosn', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'called bosn', 4, true),
  ('v2.1-en-US-preference-plan-before-execution', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'plan before execution', 4, true),
  ('v2.1-en-US-preference-wants-a-plan-before-execution', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'wants a plan before execution', 4, true),
  ('v2.1-en-US-preference-plan-before-major-changes', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'plan before major changes', 4, true),
  ('v2.1-en-US-preference-before-major-changes-are-executed', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'before major changes are executed', 4, true),
  ('v2.1-en-US-preference-should-match-the-user-language', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'should match the user language', 4, true),
  ('v2.1-en-US-preference-replying-in-english-to-english', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'replying in english to english', 4, true),
  ('v2.1-en-US-preference-replying-in-chinese-to-chinese', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'replying in chinese to chinese', 4, true),
  ('v2.1-en-US-preference-never-send-half-baked-replies', 'v2.1', 'preference', 'Preference and policy', 'en-US', 'phrase', 'never send half-baked replies', 4, true),
  -- Experience rules
  ('v2.1-zh-CN-experience-旅行', 'v2.1', 'experience', '经历与结果', 'zh-CN', 'keyword', '旅行', 4, true),
  ('v2.1-zh-CN-experience-旅游', 'v2.1', 'experience', '经历与结果', 'zh-CN', 'keyword', '旅游', 4, true),
  ('v2.1-zh-CN-experience-出差', 'v2.1', 'experience', '经历与结果', 'zh-CN', 'keyword', '出差', 4, true),
  ('v2.1-zh-CN-experience-去过', 'v2.1', 'experience', '经历与结果', 'zh-CN', 'keyword', '去过', 4, true),
  ('v2.1-zh-CN-experience-住酒店', 'v2.1', 'experience', '经历与结果', 'zh-CN', 'keyword', '住酒店', 4, true),
  ('v2.1-zh-CN-experience-体验了', 'v2.1', 'experience', '经历与结果', 'zh-CN', 'keyword', '体验了', 4, true),
  ('v2.1-zh-CN-experience-参加了', 'v2.1', 'experience', '经历与结果', 'zh-CN', 'keyword', '参加了', 4, true),
  ('v2.1-zh-CN-experience-经历过', 'v2.1', 'experience', '经历与结果', 'zh-CN', 'keyword', '经历过', 4, true),
  ('v2.1-zh-CN-experience-试过', 'v2.1', 'experience', '经历与结果', 'zh-CN', 'keyword', '试过', 4, true),
  ('v2.1-zh-CN-experience-第一次', 'v2.1', 'experience', '经历与结果', 'zh-CN', 'keyword', '第一次', 4, true),
  ('v2.1-zh-CN-experience-已发布', 'v2.1', 'experience', '经历与结果', 'zh-CN', 'keyword', '已发布', 4, true),
  ('v2.1-zh-CN-experience-已上线', 'v2.1', 'experience', '经历与结果', 'zh-CN', 'keyword', '已上线', 4, true),
  ('v2.1-zh-CN-experience-已导入', 'v2.1', 'experience', '经历与结果', 'zh-CN', 'keyword', '已导入', 4, true),
  ('v2.1-zh-CN-experience-已安装', 'v2.1', 'experience', '经历与结果', 'zh-CN', 'keyword', '已安装', 4, true),
  ('v2.1-zh-CN-experience-已更新', 'v2.1', 'experience', '经历与结果', 'zh-CN', 'keyword', '已更新', 4, true),
  ('v2.1-zh-CN-experience-已创建', 'v2.1', 'experience', '经历与结果', 'zh-CN', 'keyword', '已创建', 4, true),
  ('v2.1-zh-CN-experience-已构建', 'v2.1', 'experience', '经历与结果', 'zh-CN', 'keyword', '已构建', 4, true),
  ('v2.1-zh-CN-experience-已部署', 'v2.1', 'experience', '经历与结果', 'zh-CN', 'keyword', '已部署', 4, true),
  ('v2.1-zh-CN-experience-发布了', 'v2.1', 'experience', '经历与结果', 'zh-CN', 'keyword', '发布了', 4, true),
  ('v2.1-zh-CN-experience-上线了', 'v2.1', 'experience', '经历与结果', 'zh-CN', 'keyword', '上线了', 4, true),
  ('v2.1-zh-CN-experience-创建了', 'v2.1', 'experience', '经历与结果', 'zh-CN', 'keyword', '创建了', 4, true),
  ('v2.1-zh-CN-experience-安装了', 'v2.1', 'experience', '经历与结果', 'zh-CN', 'keyword', '安装了', 4, true),
  ('v2.1-zh-CN-experience-更新了', 'v2.1', 'experience', '经历与结果', 'zh-CN', 'keyword', '更新了', 4, true),
  ('v2.1-zh-CN-experience-导入了', 'v2.1', 'experience', '经历与结果', 'zh-CN', 'keyword', '导入了', 4, true),
  ('v2.1-zh-CN-experience-构建了', 'v2.1', 'experience', '经历与结果', 'zh-CN', 'keyword', '构建了', 4, true),
  ('v2.1-zh-CN-experience-部署了', 'v2.1', 'experience', '经历与结果', 'zh-CN', 'keyword', '部署了', 4, true),
  ('v2.1-zh-CN-experience-修复了', 'v2.1', 'experience', '经历与结果', 'zh-CN', 'keyword', '修复了', 4, true),
  ('v2.1-zh-CN-experience-排查了', 'v2.1', 'experience', '经历与结果', 'zh-CN', 'keyword', '排查了', 4, true),
  ('v2.1-zh-CN-experience-发布pr', 'v2.1', 'experience', '经历与结果', 'zh-CN', 'keyword', '发布PR', 4, true),
  ('v2.1-zh-CN-experience-成功导入', 'v2.1', 'experience', '经历与结果', 'zh-CN', 'keyword', '成功导入', 4, true),
  ('v2.1-zh-CN-experience-已完成', 'v2.1', 'experience', '经历与结果', 'zh-CN', 'keyword', '已完成', 4, true),
  ('v2.1-zh-CN-experience-完成了', 'v2.1', 'experience', '经历与结果', 'zh-CN', 'keyword', '完成了', 4, true),
  ('v2.1-zh-CN-experience-已修复', 'v2.1', 'experience', '经历与结果', 'zh-CN', 'keyword', '已修复', 4, true),
  ('v2.1-en-US-experience-travel', 'v2.1', 'experience', 'Experience', 'en-US', 'keyword', 'travel', 4, true),
  ('v2.1-en-US-experience-trip', 'v2.1', 'experience', 'Experience', 'en-US', 'keyword', 'trip', 4, true),
  ('v2.1-en-US-experience-vacation', 'v2.1', 'experience', 'Experience', 'en-US', 'keyword', 'vacation', 4, true),
  ('v2.1-en-US-experience-traveled', 'v2.1', 'experience', 'Experience', 'en-US', 'keyword', 'traveled', 4, true),
  ('v2.1-en-US-experience-hotel', 'v2.1', 'experience', 'Experience', 'en-US', 'keyword', 'hotel', 4, true),
  ('v2.1-en-US-experience-experienced', 'v2.1', 'experience', 'Experience', 'en-US', 'keyword', 'experienced', 4, true),
  ('v2.1-en-US-experience-attended', 'v2.1', 'experience', 'Experience', 'en-US', 'keyword', 'attended', 4, true),
  ('v2.1-en-US-experience-tried', 'v2.1', 'experience', 'Experience', 'en-US', 'keyword', 'tried', 4, true),
  ('v2.1-en-US-experience-went-to', 'v2.1', 'experience', 'Experience', 'en-US', 'phrase', 'went to', 4, true),
  ('v2.1-en-US-experience-first-time', 'v2.1', 'experience', 'Experience', 'en-US', 'phrase', 'first time', 4, true),
  ('v2.1-en-US-experience-created', 'v2.1', 'experience', 'Experience', 'en-US', 'keyword', 'created', 4, true),
  ('v2.1-en-US-experience-built', 'v2.1', 'experience', 'Experience', 'en-US', 'keyword', 'built', 4, true),
  ('v2.1-en-US-experience-installed', 'v2.1', 'experience', 'Experience', 'en-US', 'keyword', 'installed', 4, true),
  ('v2.1-en-US-experience-updated', 'v2.1', 'experience', 'Experience', 'en-US', 'keyword', 'updated', 4, true),
  ('v2.1-en-US-experience-patched', 'v2.1', 'experience', 'Experience', 'en-US', 'keyword', 'patched', 4, true),
  ('v2.1-en-US-experience-published', 'v2.1', 'experience', 'Experience', 'en-US', 'keyword', 'published', 4, true),
  ('v2.1-en-US-experience-released', 'v2.1', 'experience', 'Experience', 'en-US', 'keyword', 'released', 4, true),
  ('v2.1-en-US-experience-imported', 'v2.1', 'experience', 'Experience', 'en-US', 'keyword', 'imported', 4, true),
  ('v2.1-en-US-experience-launched', 'v2.1', 'experience', 'Experience', 'en-US', 'keyword', 'launched', 4, true),
  ('v2.1-en-US-experience-deployed', 'v2.1', 'experience', 'Experience', 'en-US', 'keyword', 'deployed', 4, true),
  ('v2.1-en-US-experience-was-created', 'v2.1', 'experience', 'Experience', 'en-US', 'phrase', 'was created', 4, true),
  ('v2.1-en-US-experience-was-updated', 'v2.1', 'experience', 'Experience', 'en-US', 'phrase', 'was updated', 4, true),
  ('v2.1-en-US-experience-was-installed', 'v2.1', 'experience', 'Experience', 'en-US', 'phrase', 'was installed', 4, true),
  ('v2.1-en-US-experience-was-released', 'v2.1', 'experience', 'Experience', 'en-US', 'phrase', 'was released', 4, true),
  ('v2.1-en-US-experience-was-deployed', 'v2.1', 'experience', 'Experience', 'en-US', 'phrase', 'was deployed', 4, true),
  ('v2.1-en-US-experience-smoke-tested', 'v2.1', 'experience', 'Experience', 'en-US', 'phrase', 'smoke-tested', 4, true),
  ('v2.1-en-US-experience-smoke-tested-2', 'v2.1', 'experience', 'Experience', 'en-US', 'phrase', 'smoke tested', 4, true),
  ('v2.1-en-US-experience-investigated', 'v2.1', 'experience', 'Experience', 'en-US', 'keyword', 'investigated', 4, true),
  ('v2.1-en-US-experience-triaged', 'v2.1', 'experience', 'Experience', 'en-US', 'keyword', 'triaged', 4, true),
  ('v2.1-en-US-experience-completed', 'v2.1', 'experience', 'Experience', 'en-US', 'keyword', 'completed', 4, true),
  ('v2.1-en-US-experience-fixed-successfully', 'v2.1', 'experience', 'Experience', 'en-US', 'phrase', 'fixed successfully', 4, true),
  ('v2.1-en-US-experience-successfully-imported', 'v2.1', 'experience', 'Experience', 'en-US', 'phrase', 'successfully imported', 4, true),
  -- Activity, engineering, workflow, and design rules
  ('v2.1-zh-CN-activity-开发', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '开发', 3, true),
  ('v2.1-zh-CN-activity-研发', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '研发', 3, true),
  ('v2.1-zh-CN-activity-工程', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '工程', 3, true),
  ('v2.1-zh-CN-activity-构建', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '构建', 3, true),
  ('v2.1-zh-CN-activity-写代码', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '写代码', 3, true),
  ('v2.1-zh-CN-activity-写脚本', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '写脚本', 3, true),
  ('v2.1-zh-CN-activity-脚本', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '脚本', 3, true),
  ('v2.1-zh-CN-activity-自动化', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '自动化', 3, true),
  ('v2.1-zh-CN-activity-设计', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '设计', 3, true),
  ('v2.1-zh-CN-activity-调试', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '调试', 3, true),
  ('v2.1-zh-CN-activity-部署', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '部署', 3, true),
  ('v2.1-zh-CN-activity-发布', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '发布', 3, true),
  ('v2.1-zh-CN-activity-上线', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '上线', 3, true),
  ('v2.1-zh-CN-activity-修复', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '修复', 3, true),
  ('v2.1-zh-CN-activity-排查', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '排查', 3, true),
  ('v2.1-zh-CN-activity-分析', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '分析', 3, true),
  ('v2.1-zh-CN-activity-调查', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '调查', 3, true),
  ('v2.1-zh-CN-activity-研究', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '研究', 3, true),
  ('v2.1-zh-CN-activity-阅读', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '阅读', 3, true),
  ('v2.1-zh-CN-activity-学习', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '学习', 3, true),
  ('v2.1-zh-CN-activity-练习', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '练习', 3, true),
  ('v2.1-zh-CN-activity-编写', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '编写', 3, true),
  ('v2.1-zh-CN-activity-重构', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '重构', 3, true),
  ('v2.1-zh-CN-activity-测试', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '测试', 3, true),
  ('v2.1-zh-CN-activity-联调', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '联调', 3, true),
  ('v2.1-zh-CN-activity-集成', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '集成', 3, true),
  ('v2.1-zh-CN-activity-导入', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '导入', 3, true),
  ('v2.1-zh-CN-activity-导出', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '导出', 3, true),
  ('v2.1-zh-CN-activity-同步', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '同步', 3, true),
  ('v2.1-zh-CN-activity-索引', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '索引', 3, true),
  ('v2.1-zh-CN-activity-备份', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '备份', 3, true),
  ('v2.1-zh-CN-activity-监控', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '监控', 3, true),
  ('v2.1-zh-CN-activity-可观测性', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '可观测性', 3, true),
  ('v2.1-zh-CN-activity-告警', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '告警', 3, true),
  ('v2.1-zh-CN-activity-巡检', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '巡检', 3, true),
  ('v2.1-zh-CN-activity-运行维护', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '运行维护', 3, true),
  ('v2.1-zh-CN-activity-运营维护', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '运营维护', 3, true),
  ('v2.1-zh-CN-activity-维护', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '维护', 3, true),
  ('v2.1-zh-CN-activity-配置', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '配置', 3, true),
  ('v2.1-zh-CN-activity-工作流', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '工作流', 3, true),
  ('v2.1-zh-CN-activity-流程', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '流程', 3, true),
  ('v2.1-zh-CN-activity-需求', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '需求', 3, true),
  ('v2.1-zh-CN-activity-方案', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '方案', 3, true),
  ('v2.1-zh-CN-activity-原型', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '原型', 3, true),
  ('v2.1-zh-CN-activity-交互', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '交互', 3, true),
  ('v2.1-zh-CN-activity-报表', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '报表', 3, true),
  ('v2.1-zh-CN-activity-报告', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '报告', 3, true),
  ('v2.1-zh-CN-activity-图表', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '图表', 3, true),
  ('v2.1-zh-CN-activity-趋势图', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '趋势图', 3, true),
  ('v2.1-zh-CN-activity-统计', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '统计', 3, true),
  ('v2.1-zh-CN-activity-流量', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '流量', 3, true),
  ('v2.1-zh-CN-activity-集群', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '集群', 3, true),
  ('v2.1-zh-CN-activity-快照', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '快照', 3, true),
  ('v2.1-zh-CN-activity-查询', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '查询', 3, true),
  ('v2.1-zh-CN-activity-工作区', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '工作区', 3, true),
  ('v2.1-zh-CN-activity-运行时', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '运行时', 3, true),
  ('v2.1-zh-CN-activity-提及', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '提及', 3, true),
  ('v2.1-zh-CN-activity-群聊', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '群聊', 3, true),
  ('v2.1-zh-CN-activity-飞书', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '飞书', 3, true),
  ('v2.1-zh-CN-activity-技能', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '技能', 3, true),
  ('v2.1-zh-CN-activity-记忆', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '记忆', 3, true),
  ('v2.1-zh-CN-activity-平台', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '平台', 3, true),
  ('v2.1-zh-CN-activity-产品设计', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '产品设计', 3, true),
  ('v2.1-zh-CN-activity-发布会', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '发布会', 3, true),
  ('v2.1-zh-CN-activity-画廊', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '画廊', 3, true),
  ('v2.1-zh-CN-activity-多模态', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '多模态', 3, true),
  ('v2.1-zh-CN-activity-图像理解', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '图像理解', 3, true),
  ('v2.1-zh-CN-activity-心跳检查', 'v2.1', 'activity', '工作与工程活动', 'zh-CN', 'keyword', '心跳检查', 3, true),
  ('v2.1-en-US-activity-building', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'building', 3, true),
  ('v2.1-en-US-activity-coding', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'coding', 3, true),
  ('v2.1-en-US-activity-developing', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'developing', 3, true),
  ('v2.1-en-US-activity-designing', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'designing', 3, true),
  ('v2.1-en-US-activity-debugging', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'debugging', 3, true),
  ('v2.1-en-US-activity-deploying', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'deploying', 3, true),
  ('v2.1-en-US-activity-learning', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'learning', 3, true),
  ('v2.1-en-US-activity-reading', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'reading', 3, true),
  ('v2.1-en-US-activity-studying', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'studying', 3, true),
  ('v2.1-en-US-activity-researching', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'researching', 3, true),
  ('v2.1-en-US-activity-practicing', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'practicing', 3, true),
  ('v2.1-en-US-activity-build', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'build', 3, true),
  ('v2.1-en-US-activity-patch', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'patch', 3, true),
  ('v2.1-en-US-activity-fix', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'fix', 3, true),
  ('v2.1-en-US-activity-debug', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'debug', 3, true),
  ('v2.1-en-US-activity-deploy', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'deploy', 3, true),
  ('v2.1-en-US-activity-release', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'release', 3, true),
  ('v2.1-en-US-activity-launch', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'launch', 3, true),
  ('v2.1-en-US-activity-import', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'import', 3, true),
  ('v2.1-en-US-activity-index', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'index', 3, true),
  ('v2.1-en-US-activity-sync', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'sync', 3, true),
  ('v2.1-en-US-activity-smoke-test', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'phrase', 'smoke test', 3, true),
  ('v2.1-en-US-activity-triage', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'triage', 3, true),
  ('v2.1-en-US-activity-investigate', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'investigate', 3, true),
  ('v2.1-en-US-activity-investigation', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'investigation', 3, true),
  ('v2.1-en-US-activity-workflow', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'workflow', 3, true),
  ('v2.1-en-US-activity-rule', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'rule', 3, true),
  ('v2.1-en-US-activity-policy', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'policy', 3, true),
  ('v2.1-en-US-activity-mention', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'mention', 3, true),
  ('v2.1-en-US-activity-group-chat', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'phrase', 'group chat', 3, true),
  ('v2.1-en-US-activity-feishu', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'feishu', 3, true),
  ('v2.1-en-US-activity-discord', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'discord', 3, true),
  ('v2.1-en-US-activity-sentry', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'sentry', 3, true),
  ('v2.1-en-US-activity-netlify', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'netlify', 3, true),
  ('v2.1-en-US-activity-config', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'config', 3, true),
  ('v2.1-en-US-activity-runtime', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'runtime', 3, true),
  ('v2.1-en-US-activity-workspace', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'workspace', 3, true),
  ('v2.1-en-US-activity-dsn', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'dsn', 3, true),
  ('v2.1-en-US-activity-allowlist', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'allowlist', 3, true),
  ('v2.1-en-US-activity-group-policy', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'phrase', 'group policy', 3, true),
  ('v2.1-en-US-activity-monitor', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'monitor', 3, true),
  ('v2.1-en-US-activity-monitoring', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'monitoring', 3, true),
  ('v2.1-en-US-activity-observability', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'observability', 3, true),
  ('v2.1-en-US-activity-backup', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'backup', 3, true),
  ('v2.1-en-US-activity-push', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'push', 3, true),
  ('v2.1-en-US-activity-chart', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'chart', 3, true),
  ('v2.1-en-US-activity-report', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'report', 3, true),
  ('v2.1-en-US-activity-summary', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'summary', 3, true),
  ('v2.1-en-US-activity-traffic', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'traffic', 3, true),
  ('v2.1-en-US-activity-analytics', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'analytics', 3, true),
  ('v2.1-en-US-activity-cluster', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'cluster', 3, true),
  ('v2.1-en-US-activity-snapshot', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'snapshot', 3, true),
  ('v2.1-en-US-activity-query', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'query', 3, true),
  ('v2.1-en-US-activity-product-design', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'phrase', 'product design', 3, true),
  ('v2.1-en-US-activity-prototype', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'prototype', 3, true),
  ('v2.1-en-US-activity-interaction', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'interaction', 3, true),
  ('v2.1-en-US-activity-workshop', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'workshop', 3, true),
  ('v2.1-en-US-activity-gallery', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'gallery', 3, true),
  ('v2.1-en-US-activity-research', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'research', 3, true),
  ('v2.1-en-US-activity-roadmap', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'roadmap', 3, true),
  ('v2.1-en-US-activity-requirement', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'requirement', 3, true),
  ('v2.1-en-US-activity-requirements', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'requirements', 3, true),
  ('v2.1-en-US-activity-solution', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'solution', 3, true),
  ('v2.1-en-US-activity-platform', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'platform', 3, true),
  ('v2.1-en-US-activity-pingcap', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'pingcap', 3, true),
  ('v2.1-en-US-activity-pingcomp', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'pingcomp', 3, true),
  ('v2.1-en-US-activity-tidb', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'tidb', 3, true),
  ('v2.1-en-US-activity-openclaw', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'openclaw', 3, true),
  ('v2.1-en-US-activity-mem9', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'mem9', 3, true),
  ('v2.1-en-US-activity-ai-photos', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'ai-photos', 3, true),
  ('v2.1-en-US-activity-mem9-traffic', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'mem9-traffic', 3, true),
  ('v2.1-en-US-activity-report-mem9-traffic', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'phrase', 'report mem9 traffic', 3, true),
  ('v2.1-en-US-activity-image-model', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'phrase', 'image model', 3, true),
  ('v2.1-en-US-activity-image-understanding', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'phrase', 'image understanding', 3, true),
  ('v2.1-en-US-activity-heartbeat', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'heartbeat', 3, true),
  ('v2.1-en-US-activity-hot-memory', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'phrase', 'hot memory', 3, true),
  ('v2.1-en-US-activity-warm-memory', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'phrase', 'warm memory', 3, true),
  ('v2.1-en-US-activity-cold-memory', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'phrase', 'cold memory', 3, true),
  ('v2.1-en-US-activity-promoted-to-hot', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'phrase', 'promoted to hot', 3, true),
  ('v2.1-en-US-activity-demoted-to-warm', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'phrase', 'demoted to warm', 3, true),
  ('v2.1-en-US-activity-archived-to-cold', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'phrase', 'archived to cold', 3, true),
  ('v2.1-en-US-activity-ai-driven', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'ai-driven', 3, true),
  ('v2.1-en-US-activity-ssh', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'ssh', 3, true),
  ('v2.1-en-US-activity-ec2', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'ec2', 3, true),
  ('v2.1-en-US-activity-self-improving', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'self-improving', 3, true),
  ('v2.1-en-US-activity-incremental-manifest-jsonl', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'keyword', 'incremental_manifest_jsonl', 3, true),
  ('v2.1-en-US-activity-shared-record-ingestion-flow', 'v2.1', 'activity', 'Work and engineering activity', 'en-US', 'phrase', 'shared record ingestion flow', 3, true);

COMMIT;

SELECT COUNT(*) AS rule_count
FROM `TaxonomyRule`
WHERE `version` = 'v2.1';

SELECT `category`, `lang`, COUNT(*) AS rule_count
FROM `TaxonomyRule`
WHERE `version` = 'v2.1'
GROUP BY `category`, `lang`
ORDER BY `category`, `lang`;
