-- Refresh TaxonomyRule version v2 with the expanded bilingual rule set.
-- Execute against the mem9 database, for example:
--   mysql -D mem9 < prisma/taxonomy-v2.sql

SET NAMES utf8mb4;

START TRANSACTION;

DELETE FROM `TaxonomyRule`
WHERE `version` = 'v2';

INSERT INTO `TaxonomyRule` (
  `id`,
  `version`,
  `category`,
  `label`,
  `lang`,
  `matchType`,
  `pattern`,
  `weight`,
  `enabled`
) VALUES
  ('v2-zh-CN-identity-工程师', 'v2', 'identity', '职业身份', 'zh-CN', 'keyword', '工程师', 5, true),
  ('v2-zh-CN-identity-程序员', 'v2', 'identity', '职业身份', 'zh-CN', 'keyword', '程序员', 5, true),
  ('v2-zh-CN-identity-开发者', 'v2', 'identity', '职业身份', 'zh-CN', 'keyword', '开发者', 5, true),
  ('v2-zh-CN-identity-产品经理', 'v2', 'identity', '职业身份', 'zh-CN', 'keyword', '产品经理', 5, true),
  ('v2-zh-CN-identity-设计师', 'v2', 'identity', '职业身份', 'zh-CN', 'keyword', '设计师', 5, true),
  ('v2-zh-CN-identity-创业者', 'v2', 'identity', '职业身份', 'zh-CN', 'keyword', '创业者', 5, true),
  ('v2-zh-CN-identity-研究员', 'v2', 'identity', '职业身份', 'zh-CN', 'keyword', '研究员', 5, true),
  ('v2-zh-CN-identity-学生', 'v2', 'identity', '职业身份', 'zh-CN', 'keyword', '学生', 5, true),
  ('v2-zh-CN-identity-老师', 'v2', 'identity', '职业身份', 'zh-CN', 'keyword', '老师', 5, true),
  ('v2-en-US-identity-engineer', 'v2', 'identity', 'Role', 'en-US', 'keyword', 'engineer', 5, true),
  ('v2-en-US-identity-developer', 'v2', 'identity', 'Role', 'en-US', 'keyword', 'developer', 5, true),
  ('v2-en-US-identity-programmer', 'v2', 'identity', 'Role', 'en-US', 'keyword', 'programmer', 5, true),
  ('v2-en-US-identity-product manager', 'v2', 'identity', 'Role', 'en-US', 'phrase', 'product manager', 5, true),
  ('v2-en-US-identity-designer', 'v2', 'identity', 'Role', 'en-US', 'keyword', 'designer', 5, true),
  ('v2-en-US-identity-founder', 'v2', 'identity', 'Role', 'en-US', 'keyword', 'founder', 5, true),
  ('v2-en-US-identity-researcher', 'v2', 'identity', 'Role', 'en-US', 'keyword', 'researcher', 5, true),
  ('v2-en-US-identity-student', 'v2', 'identity', 'Role', 'en-US', 'keyword', 'student', 5, true),
  ('v2-en-US-identity-teacher', 'v2', 'identity', 'Role', 'en-US', 'keyword', 'teacher', 5, true),
  ('v2-zh-CN-emotion-开心', 'v2', 'emotion', '积极情绪', 'zh-CN', 'keyword', '开心', 4, true),
  ('v2-zh-CN-emotion-高兴', 'v2', 'emotion', '积极情绪', 'zh-CN', 'keyword', '高兴', 4, true),
  ('v2-zh-CN-emotion-快乐', 'v2', 'emotion', '积极情绪', 'zh-CN', 'keyword', '快乐', 4, true),
  ('v2-zh-CN-emotion-兴奋', 'v2', 'emotion', '积极情绪', 'zh-CN', 'keyword', '兴奋', 4, true),
  ('v2-zh-CN-emotion-激动', 'v2', 'emotion', '积极情绪', 'zh-CN', 'keyword', '激动', 4, true),
  ('v2-zh-CN-emotion-满足', 'v2', 'emotion', '积极情绪', 'zh-CN', 'keyword', '满足', 4, true),
  ('v2-zh-CN-emotion-放松', 'v2', 'emotion', '积极情绪', 'zh-CN', 'keyword', '放松', 4, true),
  ('v2-zh-CN-emotion-哈哈哈', 'v2', 'emotion', '积极情绪', 'zh-CN', 'keyword', '哈哈哈', 4, true),
  ('v2-zh-CN-emotion-焦虑', 'v2', 'emotion', '消极情绪', 'zh-CN', 'keyword', '焦虑', 4, true),
  ('v2-zh-CN-emotion-难过', 'v2', 'emotion', '消极情绪', 'zh-CN', 'keyword', '难过', 4, true),
  ('v2-zh-CN-emotion-伤心', 'v2', 'emotion', '消极情绪', 'zh-CN', 'keyword', '伤心', 4, true),
  ('v2-zh-CN-emotion-生气', 'v2', 'emotion', '消极情绪', 'zh-CN', 'keyword', '生气', 4, true),
  ('v2-zh-CN-emotion-郁闷', 'v2', 'emotion', '消极情绪', 'zh-CN', 'keyword', '郁闷', 4, true),
  ('v2-zh-CN-emotion-烦躁', 'v2', 'emotion', '消极情绪', 'zh-CN', 'keyword', '烦躁', 4, true),
  ('v2-zh-CN-emotion-失望', 'v2', 'emotion', '消极情绪', 'zh-CN', 'keyword', '失望', 4, true),
  ('v2-zh-CN-emotion-崩溃', 'v2', 'emotion', '消极情绪', 'zh-CN', 'keyword', '崩溃', 4, true),
  ('v2-en-US-emotion-happy', 'v2', 'emotion', 'Positive emotion', 'en-US', 'keyword', 'happy', 4, true),
  ('v2-en-US-emotion-excited', 'v2', 'emotion', 'Positive emotion', 'en-US', 'keyword', 'excited', 4, true),
  ('v2-en-US-emotion-thrilled', 'v2', 'emotion', 'Positive emotion', 'en-US', 'keyword', 'thrilled', 4, true),
  ('v2-en-US-emotion-relieved', 'v2', 'emotion', 'Positive emotion', 'en-US', 'keyword', 'relieved', 4, true),
  ('v2-en-US-emotion-relaxed', 'v2', 'emotion', 'Positive emotion', 'en-US', 'keyword', 'relaxed', 4, true),
  ('v2-en-US-emotion-grateful', 'v2', 'emotion', 'Positive emotion', 'en-US', 'keyword', 'grateful', 4, true),
  ('v2-en-US-emotion-hahaha', 'v2', 'emotion', 'Positive emotion', 'en-US', 'keyword', 'hahaha', 4, true),
  ('v2-en-US-emotion-lol', 'v2', 'emotion', 'Positive emotion', 'en-US', 'keyword', 'lol', 4, true),
  ('v2-en-US-emotion-anxious', 'v2', 'emotion', 'Negative emotion', 'en-US', 'keyword', 'anxious', 4, true),
  ('v2-en-US-emotion-stressed', 'v2', 'emotion', 'Negative emotion', 'en-US', 'keyword', 'stressed', 4, true),
  ('v2-en-US-emotion-sad', 'v2', 'emotion', 'Negative emotion', 'en-US', 'keyword', 'sad', 4, true),
  ('v2-en-US-emotion-upset', 'v2', 'emotion', 'Negative emotion', 'en-US', 'keyword', 'upset', 4, true),
  ('v2-en-US-emotion-angry', 'v2', 'emotion', 'Negative emotion', 'en-US', 'keyword', 'angry', 4, true),
  ('v2-en-US-emotion-frustrated', 'v2', 'emotion', 'Negative emotion', 'en-US', 'keyword', 'frustrated', 4, true),
  ('v2-en-US-emotion-worried', 'v2', 'emotion', 'Negative emotion', 'en-US', 'keyword', 'worried', 4, true),
  ('v2-en-US-emotion-overwhelmed', 'v2', 'emotion', 'Negative emotion', 'en-US', 'keyword', 'overwhelmed', 4, true),
  ('v2-zh-CN-preference-喜欢', 'v2', 'preference', '偏好', 'zh-CN', 'keyword', '喜欢', 4, true),
  ('v2-zh-CN-preference-偏爱', 'v2', 'preference', '偏好', 'zh-CN', 'keyword', '偏爱', 4, true),
  ('v2-zh-CN-preference-热爱', 'v2', 'preference', '偏好', 'zh-CN', 'keyword', '热爱', 4, true),
  ('v2-zh-CN-preference-想要', 'v2', 'preference', '偏好', 'zh-CN', 'keyword', '想要', 4, true),
  ('v2-zh-CN-preference-希望', 'v2', 'preference', '偏好', 'zh-CN', 'keyword', '希望', 4, true),
  ('v2-zh-CN-preference-不喜欢', 'v2', 'preference', '偏好', 'zh-CN', 'keyword', '不喜欢', 4, true),
  ('v2-zh-CN-preference-讨厌', 'v2', 'preference', '偏好', 'zh-CN', 'keyword', '讨厌', 4, true),
  ('v2-zh-CN-preference-不想', 'v2', 'preference', '偏好', 'zh-CN', 'keyword', '不想', 4, true),
  ('v2-en-US-preference-prefer', 'v2', 'preference', 'Preference', 'en-US', 'keyword', 'prefer', 4, true),
  ('v2-en-US-preference-favorite', 'v2', 'preference', 'Preference', 'en-US', 'keyword', 'favorite', 4, true),
  ('v2-en-US-preference-love', 'v2', 'preference', 'Preference', 'en-US', 'keyword', 'love', 4, true),
  ('v2-en-US-preference-want to', 'v2', 'preference', 'Preference', 'en-US', 'phrase', 'want to', 4, true),
  ('v2-en-US-preference-would like', 'v2', 'preference', 'Preference', 'en-US', 'phrase', 'would like', 4, true),
  ('v2-en-US-preference-dislike', 'v2', 'preference', 'Preference', 'en-US', 'keyword', 'dislike', 4, true),
  ('v2-en-US-preference-hate', 'v2', 'preference', 'Preference', 'en-US', 'keyword', 'hate', 4, true),
  ('v2-en-US-preference-do not want', 'v2', 'preference', 'Preference', 'en-US', 'phrase', 'do not want', 4, true),
  ('v2-zh-CN-experience-旅行', 'v2', 'experience', '旅行经历', 'zh-CN', 'keyword', '旅行', 4, true),
  ('v2-zh-CN-experience-旅游', 'v2', 'experience', '旅行经历', 'zh-CN', 'keyword', '旅游', 4, true),
  ('v2-zh-CN-experience-出差', 'v2', 'experience', '旅行经历', 'zh-CN', 'keyword', '出差', 4, true),
  ('v2-zh-CN-experience-去过', 'v2', 'experience', '旅行经历', 'zh-CN', 'keyword', '去过', 4, true),
  ('v2-zh-CN-experience-住酒店', 'v2', 'experience', '旅行经历', 'zh-CN', 'keyword', '住酒店', 4, true),
  ('v2-zh-CN-experience-体验了', 'v2', 'experience', '经历', 'zh-CN', 'keyword', '体验了', 4, true),
  ('v2-zh-CN-experience-参加了', 'v2', 'experience', '经历', 'zh-CN', 'keyword', '参加了', 4, true),
  ('v2-zh-CN-experience-经历过', 'v2', 'experience', '经历', 'zh-CN', 'keyword', '经历过', 4, true),
  ('v2-zh-CN-experience-试过', 'v2', 'experience', '经历', 'zh-CN', 'keyword', '试过', 4, true),
  ('v2-zh-CN-experience-第一次', 'v2', 'experience', '经历', 'zh-CN', 'keyword', '第一次', 4, true),
  ('v2-en-US-experience-travel', 'v2', 'experience', 'Travel', 'en-US', 'keyword', 'travel', 4, true),
  ('v2-en-US-experience-trip', 'v2', 'experience', 'Travel', 'en-US', 'keyword', 'trip', 4, true),
  ('v2-en-US-experience-vacation', 'v2', 'experience', 'Travel', 'en-US', 'keyword', 'vacation', 4, true),
  ('v2-en-US-experience-traveled', 'v2', 'experience', 'Travel', 'en-US', 'keyword', 'traveled', 4, true),
  ('v2-en-US-experience-hotel', 'v2', 'experience', 'Travel', 'en-US', 'keyword', 'hotel', 4, true),
  ('v2-en-US-experience-experienced', 'v2', 'experience', 'Experience', 'en-US', 'keyword', 'experienced', 4, true),
  ('v2-en-US-experience-attended', 'v2', 'experience', 'Experience', 'en-US', 'keyword', 'attended', 4, true),
  ('v2-en-US-experience-tried', 'v2', 'experience', 'Experience', 'en-US', 'keyword', 'tried', 4, true),
  ('v2-en-US-experience-went to', 'v2', 'experience', 'Experience', 'en-US', 'phrase', 'went to', 4, true),
  ('v2-en-US-experience-first time', 'v2', 'experience', 'Experience', 'en-US', 'phrase', 'first time', 4, true),
  ('v2-zh-CN-activity-开发', 'v2', 'activity', '工作活动', 'zh-CN', 'keyword', '开发', 3, true),
  ('v2-zh-CN-activity-构建', 'v2', 'activity', '工作活动', 'zh-CN', 'keyword', '构建', 3, true),
  ('v2-zh-CN-activity-写代码', 'v2', 'activity', '工作活动', 'zh-CN', 'keyword', '写代码', 3, true),
  ('v2-zh-CN-activity-设计', 'v2', 'activity', '工作活动', 'zh-CN', 'keyword', '设计', 3, true),
  ('v2-zh-CN-activity-调试', 'v2', 'activity', '工作活动', 'zh-CN', 'keyword', '调试', 3, true),
  ('v2-zh-CN-activity-部署', 'v2', 'activity', '工作活动', 'zh-CN', 'keyword', '部署', 3, true),
  ('v2-zh-CN-activity-学习', 'v2', 'activity', '学习活动', 'zh-CN', 'keyword', '学习', 3, true),
  ('v2-zh-CN-activity-阅读', 'v2', 'activity', '学习活动', 'zh-CN', 'keyword', '阅读', 3, true),
  ('v2-zh-CN-activity-读书', 'v2', 'activity', '学习活动', 'zh-CN', 'keyword', '读书', 3, true),
  ('v2-zh-CN-activity-研究', 'v2', 'activity', '学习活动', 'zh-CN', 'keyword', '研究', 3, true),
  ('v2-zh-CN-activity-练习', 'v2', 'activity', '学习活动', 'zh-CN', 'keyword', '练习', 3, true),
  ('v2-zh-CN-activity-运动', 'v2', 'activity', '日常活动', 'zh-CN', 'keyword', '运动', 3, true),
  ('v2-zh-CN-activity-跑步', 'v2', 'activity', '日常活动', 'zh-CN', 'keyword', '跑步', 3, true),
  ('v2-zh-CN-activity-健身', 'v2', 'activity', '日常活动', 'zh-CN', 'keyword', '健身', 3, true),
  ('v2-zh-CN-activity-做饭', 'v2', 'activity', '日常活动', 'zh-CN', 'keyword', '做饭', 3, true),
  ('v2-zh-CN-activity-聊天', 'v2', 'activity', '日常活动', 'zh-CN', 'keyword', '聊天', 3, true),
  ('v2-en-US-activity-building', 'v2', 'activity', 'Building', 'en-US', 'keyword', 'building', 3, true),
  ('v2-en-US-activity-coding', 'v2', 'activity', 'Building', 'en-US', 'keyword', 'coding', 3, true),
  ('v2-en-US-activity-developing', 'v2', 'activity', 'Building', 'en-US', 'keyword', 'developing', 3, true),
  ('v2-en-US-activity-designing', 'v2', 'activity', 'Building', 'en-US', 'keyword', 'designing', 3, true),
  ('v2-en-US-activity-debugging', 'v2', 'activity', 'Building', 'en-US', 'keyword', 'debugging', 3, true),
  ('v2-en-US-activity-deploying', 'v2', 'activity', 'Building', 'en-US', 'keyword', 'deploying', 3, true),
  ('v2-en-US-activity-learning', 'v2', 'activity', 'Learning', 'en-US', 'keyword', 'learning', 3, true),
  ('v2-en-US-activity-reading', 'v2', 'activity', 'Learning', 'en-US', 'keyword', 'reading', 3, true),
  ('v2-en-US-activity-studying', 'v2', 'activity', 'Learning', 'en-US', 'keyword', 'studying', 3, true),
  ('v2-en-US-activity-researching', 'v2', 'activity', 'Learning', 'en-US', 'keyword', 'researching', 3, true),
  ('v2-en-US-activity-practicing', 'v2', 'activity', 'Learning', 'en-US', 'keyword', 'practicing', 3, true),
  ('v2-en-US-activity-working out', 'v2', 'activity', 'Daily activity', 'en-US', 'phrase', 'working out', 3, true),
  ('v2-en-US-activity-running', 'v2', 'activity', 'Daily activity', 'en-US', 'keyword', 'running', 3, true),
  ('v2-en-US-activity-cooking', 'v2', 'activity', 'Daily activity', 'en-US', 'keyword', 'cooking', 3, true),
  ('v2-en-US-activity-chatting', 'v2', 'activity', 'Daily activity', 'en-US', 'keyword', 'chatting', 3, true),
  ('v2-en-US-activity-shopping', 'v2', 'activity', 'Daily activity', 'en-US', 'keyword', 'shopping', 3, true);

COMMIT;

SELECT COUNT(*) AS rule_count
FROM `TaxonomyRule`
WHERE `version` = 'v2';

SELECT `category`, `lang`, COUNT(*) AS rule_count
FROM `TaxonomyRule`
WHERE `version` = 'v2'
GROUP BY `category`, `lang`
ORDER BY `category`, `lang`;
