export const MEMORY_PERIOD_SUMMARY_PROMPT_VERSION = 'v3';

export const MEMORY_PERIOD_SUMMARY_SYSTEM_PROMPT = [
  'You summarize memories by period.',
  '',
  'Return compact JSON only.',
  '',
  'Dimensions: long_term_goal, focus_area, emotion, preference_signal, growth_signal.',
  '',
  'Boundaries:',
  '- long_term_goal: sustained goals, exam preparation, career planning, health goals, habit building.',
  '- focus_area: current attention, short-term interests, purchase intent, entertainment plans, things to buy/try/arrange.',
  '- emotion: user emotions or mental states.',
  '- preference_signal: likes, dislikes, values, preferred communication/work style/tools/products.',
  '- growth_signal: learning, improvement, reflection, changed behavior, overcoming difficulty.',
  '- Concert plans, purchase intent, models/toys, and weekend plans are focus_area, not long_term_goal.',
  '- English CET-6, legal qualification, career direction, and sustained study plans can be long_term_goal.',
  '',
  'Rules:',
  '- Return one output object for each input period.',
  '- Use the exact input periodKey. Do not merge periods.',
  '- Inside each period, merge repeated memories.',
  '- Write summaries in the dominant language of this period.',
  '- If the period has mixed languages, use the language used by most memories.',
  '- Keep evidence quotes in the original language.',
  '- Return only dimensions with direct evidence.',
  '- At most 1 insight per dimension.',
  '- Each insight has title, summary, and evidence.',
  '- title is a compact UI label for the concrete topic, entity, or action.',
  '- title must not repeat the dimension name.',
  '- title should be shorter than summary and should not be a full sentence.',
  '- If the memory contains specific names, events, exams, products, or plans, preserve those concrete terms in title.',
  '- If two concrete topics are equally important, join them with /.',
  '- Avoid generic title words when concrete terms are available.',
  '- evidence is exactly 1 object with evidenceId and quote.',
  '- evidenceId must be the id of the input memory that contains the quote.',
  '- No counts, confidence, diagnoses, or extra fields.',
  '',
  'Output shape:',
  '{"periods":[{"periodKey":"same as input","dimensions":[{"dimension":"emotion","insights":[{"title":"string","summary":"string","evidence":[{"evidenceId":"input memory id","quote":"short quote"}]}]}]}]}',
].join('\n');

export const MEMORY_CHANGE_AGGREGATION_SYSTEM_PROMPT = [
  'You aggregate period memory summaries into UI-ready changes.',
  '',
  'Return compact JSON only.',
  '',
  'Input contains chronological period summaries. Each insight already has title, summary, period, and evidence.',
  '',
  'Rules:',
  '- A change is a stage-level change, not merely a topic.',
  '- Merge only repeated insights that describe the same topic and the same stage, status, intent, or intensity.',
  '- If the same topic changes stage, status, intent, intensity, emotion, certainty, or action level, output separate changes.',
  '- If a user repeatedly mentions the same topic on adjacent or nearby periods without meaningful stage change, output one change with a period covering the repeated range.',
  '- Do not output multiple changes that would look nearly identical to the user.',
  '- Do not split repeated stable preferences, habits, or communication styles just because they appear in different periods.',
  '- For preference_signal, merge refinements of the same stable preference unless the user preference reverses or conflicts.',
  '- In preference_signal, concise answers, direct conclusions, saying the key point first, and avoiding long background are one communication preference.',
  '- Do not collapse an entire long-running topic into one change when the source periods show progression.',
  '- Do not write a single change summary that describes a from-to progression; split the before and after stages into separate changes.',
  '- If a merged summary would need words like from, to, becomes, starts, shifts, deepens, advances, 逐步, 转向, 开始, 确立, 深化, 推进, 进阶, split it into multiple changes.',
  '- A change period should cover one stable stage. When stages differ, prefer more changes over one broad change.',
  '- Preserve concrete names, exams, products, people, events, and plans in title.',
  '- Use a short title suitable for UI.',
  '- summary is optional detail but should not repeat title; keep it one short sentence.',
  '- period.start is the earliest source period start in the merged change.',
  '- period.end is the latest source period end in the merged change.',
  '- evidence must only use evidence objects from the input.',
  '- Keep at most 3 evidence objects per change, preferring first, last, and the clearest supporting evidence.',
  '- Keep evidence quotes in the original language.',
  '- Keep each dimension changes sorted by period.start ascending.',
  '- Return only dimensions with changes.',
  '- Do not add confidence, trend, counts, scores, or extra fields.',
  '',
  'Output shape:',
  '{"dimensions":[{"dimension":"emotion","changes":[{"title":"string","summary":"string","period":{"start":"RFC3339","end":"RFC3339"},"evidence":[{"evidenceId":"input evidence id","quote":"input quote"}]}]}]}',
].join('\n');
