export const MEMORY_PERIOD_SUMMARY_PROMPT_VERSION = 'v4';

export const MEMORY_PERIOD_SUMMARY_SYSTEM_PROMPT = [
  'You summarize memories by period.',
  '',
  'Return compact JSON only.',
  '',
  'Dimensions: long_term_goal, focus_area, emotion, preference_signal, growth_signal.',
  '',
  'Boundaries:',
  '- long_term_goal: sustained goals, exam preparation, career planning, health goals, habit building.',
  '- focus_area: current attention, short-term interests, purchase intent, entertainment plans, things to buy/try/arrange.',
  '- emotion: user emotions or mental states.',
  '- preference_signal: likes, dislikes, values, preferred communication/work style/tools/products.',
  '- growth_signal: learning, improvement, reflection, changed behavior, overcoming difficulty.',
  '- Concert plans, purchase intent, models/toys, and weekend plans are focus_area, not long_term_goal.',
  '- English CET-6, legal qualification, career direction, and sustained study plans can be long_term_goal.',
  '',
  'Rules:',
  '- Return one output object for each input period.',
  '- Use the exact input periodKey. Do not merge periods.',
  '- Inside each period, merge repeated memories.',
  '- Write summaries in the dominant language of this period.',
  '- If the period has mixed languages, use the language used by most memories.',
  '- Keep evidence quotes in the original language.',
  '- Return only dimensions with direct evidence.',
  '- At most 3 insights per dimension.',
  '- Split unrelated concrete topics inside the same dimension into separate insights.',
  '- Each insight has title, summary, and evidence.',
  '- title is a compact UI label for the concrete topic, entity, or action.',
  '- title must not repeat the dimension name.',
  '- title should be shorter than summary and should not be a full sentence.',
  '- If the memory contains specific names, events, exams, products, or plans, preserve those concrete terms in title.',
  '- If two concrete topics are equally important, join them with /.',
  '- Avoid generic title words when concrete terms are available.',
  '- evidence is exactly 1 object with evidenceId and quote.',
  '- evidenceId must be the id of the input memory that contains the quote.',
  '- No counts, confidence, diagnoses, or extra fields.',
  '',
  'Output shape:',
  '{"periods":[{"periodKey":"same as input","dimensions":[{"dimension":"emotion","insights":[{"title":"string","summary":"string","evidence":[{"evidenceId":"input memory id","quote":"short quote"}]}]}]}]}',
].join('\n');

export const MEMORY_CHANGE_AGGREGATION_SYSTEM_PROMPT = [
  'Aggregate period memory summaries into UI-ready changes. Return compact JSON only.',
  '',
  'Input schema: {"p":[{"r":{"s":"start","e":"end"},"d":[{"k":"dimension","i":[{"t":"title","s":"summary","e":[{"id":"evidenceId","q":"quote"}]}]}]}]}',
  'Output schema: {"d":[{"k":"dimension","c":[{"t":"title","s":"summary","p":{"s":"start","e":"end"},"e":["evidenceId"]}]}]}',
  '',
  'Dimensions: long_term_goal, focus_area, emotion, preference_signal, growth_signal.',
  '',
  'Rules:',
  '- Scan every input period and every input dimension group.',
  '- For every input dimension that has insights, output that dimension with at least one change unless all its insights are invalid.',
  '- Do not drop dimensions to keep the response short.',
  '- A change is one stable stage, not just one topic.',
  '- Merge same topic only when stage/status/intent/intensity is also the same.',
  '- Split when a topic changes stage/status/intent/intensity/emotion/certainty/action.',
  '- Do not summarize a from-to progression in one change; split stages instead.',
  '- Split if one summary would need: from/to/becomes/starts/shifts/deepens/advances/逐步/转向/开始/确立/深化/推进/进阶.',
  '- Do not output near-duplicate changes.',
  '- For stable preferences/habits/communication styles, merge repeated refinements unless they conflict.',
  '- For preference_signal, concise answers/direct conclusions/key point first/no long background are one communication preference.',
  '- t: short UI title with concrete names. s: one short sentence, not a title repeat.',
  '- p.s and p.e cover the source periods merged into this change.',
  '- e contains input evidence ids only, not quote objects. Use at most 3 ids: first, last, clearest.',
  '- Keep changes sorted by p.s. Return only dimensions with changes. No extra fields. Minify JSON.',
].join('\n');
